apiVersion: v1
kind: Namespace
metadata:
  name: thetiptop-dev
  labels:
    env: dev
    app: thetiptop
---
apiVersion: v1
kind: Namespace
metadata:
  name: thetiptop-preprod
  labels:
    env: preprod
    app: thetiptop
---
apiVersion: v1
kind: Namespace
metadata:
  name: thetiptop-prod
  labels:
    env: prod
    app: thetiptop
