---
- name: Créer le répertoire Traefik
  ansible.builtin.file:
    path: "{{ traefik_install_dir }}"
    state: directory
    mode: "0755"

- name: Déposer docker-compose Traefik
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ traefik_install_dir }}/docker-compose.yml"
    mode: "0644"

- name: Déployer Traefik (Compose v2)
  community.docker.docker_compose_v2:
    project_src: "{{ traefik_install_dir }}"
    state: present
    pull: always
