apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: thetiptop-preprod
  labels:
    app: frontend
    env: preprod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        env: preprod
    spec:
      containers:
        - name: frontend
          image: HARBOR_REGISTRY/thetiptop-preprod/frontend:IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 75m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 384Mi
      imagePullSecrets:
        - name: harbor-secret
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: thetiptop-preprod
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
