# Overlay DEV – déployer sur le cluster dédié dev (Option B : 3 clusters)
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: thetiptop-dev
resources:
  - ../../base
  - namespace.yaml
images:
  - name: harbor.example.com/thetiptop/backend:latest
    newName: harbor.example.com/thetiptop-dev/backend
    newTag: latest
  - name: harbor.example.com/thetiptop/frontend:latest
    newName: harbor.example.com/thetiptop-dev/frontend
    newTag: latest
